version: '3'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile-backend-dev
        container_name: backend
        links:
            - db
        depends_on:
            - db
        expose:
            - '8080'
            - '9229'
        ports:
            - '8080:8080' # for main server
            - '9229:9229' # for vscode debugger
        volumes:
            - ./:/usr/src/app
    db:
        image: postgres:9.6
        container_name: db
        expose:
            - '5432'
        ports:
            - '5432:5432'
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
