version: '3'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile-backend-prod
        container_name: augustus-backend
        links:
            - db
        depends_on:
            - db
        expose:
            - '8080'
        environment:
            # Necessary for nginx-proxy. Must be unique between all apps being proxied to.
            # nginx-proxy can look into each container and grab its VIRTUAL_HOST in order to dynamically generate the nginx config block for it.
            VIRTUAL_HOST: augustus.io
            VIRTUAL_PORT: 8080
            LETSENCRYPT_HOST: augustus.io
            LETSENCRYPT_EMAIL: rchen1992@gmail.com
    db:
        image: postgres:9.6
        container_name: augustus-db
        expose:
            - '5432'
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data

networks:
    default:
        external:
            name: nginx-proxy
